# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ""
author: the brainplotlib developers and contributors
logo: brainplotlib_logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/feilong/brainplotlib  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_substitutions:
    gallery: |
      ````{panels}
      :column: col-4 m-0
      :body: p-0

      ```{link-button} /examples/save_image
      :text: Save the high-res image
      :type: ref
      :classes: stretched-link btn-block m-0 p-0
      ```
      ^^^
      ```{glue:figure} save_image
      ```

      ---

      ```{link-button} /examples/plot_colorbar
      :text: Plot a colorbar
      :type: ref
      :classes: stretched-link btn-block m-0 p-0
      ```
      ^^^
      ```{glue:figure} with_colorbar
      ```

      ---

      ```{link-button} /examples/different_cmaps
      :text: Different colormaps
      :type: ref
      :classes: stretched-link btn-block m-0 p-0
      ```
      ^^^
      ```{glue:figure} different_cmaps
      ```

      ````
      ````{panels}
      :column: col-4 m-0
      :body: p-0

      ```{link-button} /examples/different_resolutions
      :text: Different data resolutions
      :type: ref
      :classes: stretched-link btn-block m-0 p-0
      ```
      ^^^
      ```{glue:figure} different_resolutions
      ```

      ---
 
      ```{link-button} /examples/cortical_masks
      :text: Handling cortical masks
      :type: ref
      :classes: stretched-link btn-block m-0 p-0
      ```
      ^^^
      ```{glue:figure} cortical_masks
      ```

      ---

      ```{link-button} /examples/different_surfaces
      :text: Alternative surface types
      :type: ref
      :classes: stretched-link btn-block m-0 p-0
      ```
      ^^^
      ```{glue:figure} different_surfaces
      ```

      ````
    gallery_link : |
      ---
      [**<< Go back to the gallery of examples**](/examples/index)
